### PR TITLE
fix(productSync): Update categories before categoryOrderHints

### LINKED ISSUE #218: CategoryOrderHints are being imported before the product is linked with a category
see https://github.com/sphereio/sphere-node-product-csv-sync/issues/163

### PR DESCRIPTION
**Pull request by junajan**
#### Summary
This PR fixes #218 

#### Description
When generating product update actions category actions should be placed before categoryOrderHint actions so we can add product to category and create a categoryOrderHint in one request.

#### Todo

- Tests
    - [x] Unit
    - [ ] Integration
    - [ ] Acceptance
- [ ] Documentation

### CODE REVIEW

**Comment by adnasa** [comment]
After a short discussion with @wizzy25 ,
I would rather see that the `setCategoryHint` is moved out of the `actionMapsBase` and that you create a separate mapper for this action, with the specified criteria (such as `categories` should be linked to the product) to fulfil the action

code
```
// in utils/product.coffee
const actionCategoryOrderHint = {
  action: 'setCategoryOrderHint',
  key: 'categoryOrderHints',
}

actionsMapCategoryOrderHint: () => {
  const action = this.buildBaseAttributesAction(item, diff, old_obj)
  // do your thing then push to the actions list!
}


// in product-sync.coffee
// below 'categories' mapper configuration
allActions.push(
  this._mapActionOrNot(
    ('categoryOrderHint'),
    () => this._utils.actionsMapCategoryOrderHint(diff)
  )
)
```

Once you take this approach, make sure to remove the `setCategoryHint` from `actionsBaseList`, and you can move the `categories` action configuration back to it original order

**Comment by junajan** [comment]
@wizzy25 @adnasa - I refactored code according to your comments.. please check it now.

**Comment by junajan** [comment]
@wizzy25 can you please merge this PR? I am not authorized to do that 😢

**Comment by wizzy25** [comment]
@emmenko Could you review and merge this PR? I don't have write access on this repo

File: src/coffee/sync/utils/product.coffee [hunk 1]
```diff
@@ -93,27 +93,38 @@ class ProductUtils extends BaseUtils
...
+      key: 'categoryOrderHints'
+    }
+
+    action = @_buildBaseAttributesAction(actionCategoryOrderHint, diff, old_obj)
+    if action and action.categoryOrderHints isnt undefined
+      # if the the category order hint was changed from {} to not existant
+      actions = Object.keys(action.categoryOrderHints)
+        .map (categoryId) ->
+          orderHint = action.categoryOrderHints[categoryId]
+          if orderHint is null or orderHint is undefined
```
Comment (hisabimbola) [inline src/coffee/sync/utils/product.coffee]: in coffee this line is same as `orderHint?`
