### PR TITLE
fix(inventory.coffee): fix error in restockable in days

### LINKED ISSUE #276: fix error in RestockableInDays
### Description
Fix update error  in RestockableInDays when new value is passed.

### Expected Behavior
Should update the RestockableIndays when new one is passed.

### Current Behavior
Not showing the new value for RestockableIndays.

### PR DESCRIPTION
**Pull request by Babanila**
#### Summary
Fix update error in RestockableInDays

#### Description
No update is shown when new RestockableInDays value is passed.

#### Todo

- Tests
    - [x] Unit
    - [x] Integration

closes #276

### CODE REVIEW

File: src/coffee/sync/utils/inventory.coffee [hunk 1]
```diff
@@ -49,23 +49,24 @@ class InventoryUtils extends BaseUtils
   # diff - {Object} The result of diff from `jsondiffpatch`
   #
   # Returns {Array} The list of actions, or empty if there are none
-  actionsMapRestockableInDays: (diff) ->
+  actionsMapRestockableInDays: (diff, old_obj) ->
     actions = []
     if diff.restockableInDays
       if _.isArray(diff.restockableInDays)
         size = _.size(diff.restockableInDays)
+        console.log size
```
Comment (LEQADA) [inline src/coffee/sync/utils/inventory.coffee]: It probably was a testing print? :slightly_smiling_face:

File: src/coffee/sync/utils/inventory.coffee [hunk 2]
```diff
@@ -49,23 +49,23 @@ class InventoryUtils extends BaseUtils
   # diff - {Object} The result of diff from `jsondiffpatch`
   #
   # Returns {Array} The list of actions, or empty if there are none
-  actionsMapRestockableInDays: (diff) ->
+  actionsMapRestockableInDays: (diff, old_obj) ->
```
Comment (hajoeichler) [inline src/coffee/sync/utils/inventory.coffee]: Why do you get the old_obj here, but you don't use it.

File: src/coffee/sync/utils/inventory.coffee [hunk 3]
```diff
@@ -49,23 +49,23 @@ class InventoryUtils extends BaseUtils
...
     actions = []
     if diff.restockableInDays
       if _.isArray(diff.restockableInDays)
         size = _.size(diff.restockableInDays)
         a =
           action: 'setRestockableInDays'
-        if size is 1
-          a.restockableInDays = diff.restockableInDays[0]
-        else if size is 2
+        if size is 2
```
Comment (hajoeichler) [inline src/coffee/sync/utils/inventory.coffee]: If you don't change the order of the if/else statement, the actual change is one line.
